[22/08/21]: Scheduled job on Cores-MacBook-Pro.local

diff --git a/scripts/takeout b/scripts/takeout
--- a/scripts/takeout
+++ b/scripts/takeout
@@ -17,12 +17,12 @@
 
 if [ -d "$1" ] 
 then
-cd "$1" 
+	cd "$1" 
 fi 
 
 for FILE in *
 do
-	mv "$FILE" ../
+	mv "$FILE" ../ || (echo "Error moving files"; exit 1)
 done
 rm -fr "$(pwd)"
 exit
